name: Release APK

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ${{ github.workspace }}/.dart_tool
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.8

      - run: dart pub get

      - name: Analyze project source
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Run tests
        run: flutter test

      - id: version
        run: |
          APP_VERSION=$(grep '^version:' pubspec.yaml | awk '{print $2}')
          echo "app_version=$APP_VERSION" >> $GITHUB_ENV
          echo "App version: $APP_VERSION"

      - id: last_release
        run: |
          LAST_RELEASE=$(gh release list --limit 1 --json tagName -q '.[0].tagName' || echo "none")
          echo "last_release=$LAST_RELEASE" >> $GITHUB_ENV
          echo "App latest release: $LAST_RELEASE"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create or update tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -f ${{ env.app_version }}
          git push origin ${{ env.app_version }} --force

      - name: Build release APK if version changed
        if: ${{ env.app_version != env.last_release }}
        run: flutter build apk --release

      - name: Use existing APK if version same
        if: ${{ env.app_version == env.last_release }}
        run: |
          echo "Version unchanged ($app_version) â€” reusing previous APK."
          mkdir -p build/app/outputs/flutter-apk
          gh release download "$app_version" -p "*.apk" -D build/app/outputs/flutter-apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create or update GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.app_version }}
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
